apiVersion: v1
kind: Service
metadata:
  name: payments-bad-readiness
  namespace: rollout-lab
spec:
  selector:
    app: payments-bad-readiness
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-bad-readiness
  namespace: rollout-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-bad-readiness
  template:
    metadata:
      labels:
        app: payments-bad-readiness
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0
          args:
            - -listen=:5678
            - -text=bad readiness demo
          ports:
            - name: http
              containerPort: 5678
          readinessProbe:
            httpGet:
              path: /not-found
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
