apiVersion: v1
kind: Service
metadata:
  name: payments-bad-selector
  namespace: rollout-lab
spec:
  selector:
    app: label-that-does-not-exist
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-bad-selector
  namespace: rollout-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-bad-selector
  template:
    metadata:
      labels:
        app: payments-bad-selector
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0
          args:
            - -listen=:5678
            - -text=service selector mismatch demo
          ports:
            - name: http
              containerPort: 5678
