apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-canary
  namespace: rollout-lab
  labels:
    app: payments-canary
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-canary
      track: canary
  template:
    metadata:
      labels:
        app: payments-canary
        track: canary
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0
          args:
            - -listen=:5678
            - -text=BAD CANARY VERSION - rollback needed
          ports:
            - name: http
              containerPort: 5678
