apiVersion: v1
kind: Service
metadata:
  name: payments-canary
  namespace: rollout-lab
spec:
  selector:
    app: payments-canary
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-stable
  namespace: rollout-lab
  labels:
    app: payments-canary
    track: stable
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payments-canary
      track: stable
  template:
    metadata:
      labels:
        app: payments-canary
        track: stable
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0
          args:
            - -listen=:5678
            - -text=payments-api stable
          ports:
            - name: http
              containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-canary
  namespace: rollout-lab
  labels:
    app: payments-canary
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-canary
      track: canary
  template:
    metadata:
      labels:
        app: payments-canary
        track: canary
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0
          args:
            - -listen=:5678
            - -text=payments-api canary
          ports:
            - name: http
              containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
